import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

def install():
 fields={
 "Company":[{"fieldname":"forex_forward_contract_accounts","label":"Forex / Forward Contract Accounts","fieldtype":"Section Break","insert_after":"default_payable_account"},{"fieldname":"allow_forward_overhedging","label":"Allow Forward Overhedging","fieldtype":"Check","insert_after":"forex_forward_contract_accounts"},{"fieldname":"enable_auto_forward_settlement_gl","label":"Enable Automatic Forward Settlement GL","fieldtype":"Check","insert_after":"allow_forward_overhedging"},{"fieldname":"enable_forward_mtm_gl","label":"Enable Forward MTM GL","fieldtype":"Check","insert_after":"enable_auto_forward_settlement_gl"},{"fieldname":"forex_gain_account","label":"Forex Gain Account","fieldtype":"Link","options":"Account","insert_after":"enable_forward_mtm_gl"},{"fieldname":"forex_loss_account","label":"Forex Loss Account","fieldtype":"Link","options":"Account","insert_after":"forex_gain_account"},{"fieldname":"forward_contract_gain_account","label":"Forward Contract Gain Account","fieldtype":"Link","options":"Account","insert_after":"forex_loss_account"},{"fieldname":"forward_contract_loss_account","label":"Forward Contract Loss Account","fieldtype":"Link","options":"Account","insert_after":"forward_contract_gain_account"},{"fieldname":"forex_bank_charge_account","label":"Forex Bank Charge Account","fieldtype":"Link","options":"Account","insert_after":"forward_contract_loss_account"},{"fieldname":"forward_mtm_gain_account","label":"Forward MTM Unrealized Gain Account","fieldtype":"Link","options":"Account","insert_after":"forex_bank_charge_account"},{"fieldname":"forward_mtm_loss_account","label":"Forward MTM Unrealized Loss Account","fieldtype":"Link","options":"Account","insert_after":"forward_mtm_gain_account"},{"fieldname":"forward_mtm_balance_account","label":"Forward MTM Asset / Liability Account","fieldtype":"Link","options":"Account","insert_after":"forward_mtm_loss_account"},{"fieldname":"default_forex_cost_center","label":"Default Forex Cost Center","fieldtype":"Link","options":"Cost Center","insert_after":"forward_mtm_balance_account"}],
 "Sales Order":[{"fieldname":"forex_forward_contract_section","label":"Forex / Forward Contract","fieldtype":"Section Break","insert_after":"currency_and_price_list"},{"fieldname":"forward_contract_required","label":"Forward Contract Required","fieldtype":"Check","insert_after":"forex_forward_contract_section"},{"fieldname":"forward_booked_amount","label":"Forward Booked Amount","fieldtype":"Currency","options":"currency","read_only":1,"allow_on_submit":1,"insert_after":"forward_contract_required"},{"fieldname":"forward_available_amount","label":"Forward Available Amount","fieldtype":"Currency","options":"currency","read_only":1,"allow_on_submit":1,"insert_after":"forward_booked_amount"},{"fieldname":"unhedged_amount","label":"Unhedged Amount","fieldtype":"Currency","options":"currency","read_only":1,"allow_on_submit":1,"insert_after":"forward_available_amount"},{"fieldname":"hedge_percentage","label":"Hedge %","fieldtype":"Percent","read_only":1,"allow_on_submit":1,"insert_after":"unhedged_amount"}],
 "Sales Invoice":[{"fieldname":"forex_forward_contract_section","label":"Forex / Forward Contract","fieldtype":"Section Break","insert_after":"currency_and_price_list"},{"fieldname":"forward_contract","label":"Forward Contract","fieldtype":"Link","options":"Forward Contract","insert_after":"forex_forward_contract_section"},{"fieldname":"forward_contract_rate","label":"Forward Contract Rate","fieldtype":"Float","read_only":1,"insert_after":"forward_contract"},{"fieldname":"forward_contract_amount","label":"Forward Contract Amount","fieldtype":"Currency","read_only":1,"insert_after":"forward_contract_rate"},{"fieldname":"forward_utilized_amount","label":"Forward Utilized Amount","fieldtype":"Currency","read_only":1,"allow_on_submit":1,"insert_after":"forward_contract_amount"},{"fieldname":"forward_available_amount","label":"Forward Available Amount","fieldtype":"Currency","read_only":1,"insert_after":"forward_utilized_amount"}],
 "Payment Entry":[{"fieldname":"forex_forward_contract_section","label":"Forex / Forward Contract","fieldtype":"Section Break","insert_after":"reference_no"},{"fieldname":"forward_contract","label":"Forward Contract","fieldtype":"Link","options":"Forward Contract","insert_after":"forex_forward_contract_section"},{"fieldname":"forward_contract_utilization","label":"Forward Contract Utilization","fieldtype":"Link","options":"Forward Contract Utilization","insert_after":"forward_contract"},{"fieldname":"actual_bank_rate","label":"Actual Bank Realization Rate","fieldtype":"Float","insert_after":"forward_contract_utilization"}]}
 create_custom_fields(fields,update=True)
 if not frappe.db.exists("Role","Forex Manager"): frappe.get_doc({"doctype":"Role","role_name":"Forex Manager","desk_access":1}).insert(ignore_permissions=True)
 frappe.db.commit()
